- name: ensure cell connection is configured
  become: yes
  template:
    src: network-manager/cell.nmconnection.j2
    dest: /etc/NetworkManager/system-connections/cell.nmconnection
    owner: root
    group: root
    mode: 0600
  notify: reload network-manager

  #- name: ensure cell reset on sleep
  #  become: yes
  #  template:
  # src: system-sleep/reset-cell-modem.j2
  #  dest: /usr/lib/systemd/system-sleep/reset-cell-modem
  # owner: root
  # group: root
  # mode: '0755'
