version: '3.1'
services:
  postgres:
    image: timescale/timescaledb:latest-pg12
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "avena"
      POSTGRES_DB: "avena"
      TIMESCALEDB_TELEMETRY: "off"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/schema:/docker-entrypoint-initdb.d
volumes:
  postgres:
