#!/bin/ash

timestamp=`date +%Y/%m/%d-%H:%M:%S`
echo "go-dolly: Called at $timestamp"

config_path="/config/rclone/rclone.conf"
data_path="/data/test/can"
remote_name="remotebox"
remote_path="isoblue_rclone"

if [ ! -f $config_path ] || [ "$override" == "1" ]
then
  echo "go-dolly: Creating new config file as it did not exist or the override variable was set"
  mkdir -p /config/rclone
  echo -en "[$remote_name]\ntype = ${type}\nbox_sub_type = ${box_sub_type}\ntoken = ${token}" > $config_path
else
  echo "go-dolly: Using existing config file"
fi

echo "go-dolly: Calling rclone"
rclone copy --progress --local-no-check-updated --compress-level=$clvl --checkers=$numcheckers --bwlimit=$bwlimit --log-level DEBUG $data_path $remote_name:$remote_path
