#!/bin/bash

#/app/gps-exporter postgress://$db_user:$db_password@$db_host:$db_port/$db_database /data -f "$from" -l $segment_length --append > /proc/1/fd/1  2>&1
/app/gps-exporter postgress://avena:password@postgres/avena /data -f "2021-03-05 07:00:00" -l 60 --append
