# Name of the test. Shown on github as $name/$jobname
name: Integration Tests

# When should we run this file?
# TODO: When a maintainer of the repo pushes to an open PR, it runs the file twice.
# Should fix in the future. There are a lot of intricacies with non-maintainers
on:
  push:
  pull_request:

jobs:
  integration-tests:
    strategy:
      # So the matrix idea is that it runs the job for each service in parallel
      # Our convention is that a service is a folder under the `services`  
      # directory with the nessicary files to make a docker container plus a
      # docker-compose-test.yml file for integration testing
      matrix:
        service:
          - gps2tsdb
          - oada_upload
          - cell_logger
          - can_watchdog
          - can_logger  
          - socketcand

    runs-on: ubuntu-latest

    steps:
        # Checkout the latest pushed version of the test
      - name: Checkout
        uses: actions/checkout@v3

        # If the service has a docker-compose-test.yml file, execute it and use the
        # exit code as the exit code for the test
      - name: Integration tests
        run: |
          service=${{ matrix.service }}
          compose_test_file=docker-compose-test.yml
          echo "Checking if test script is found for service $service"
          if test -f "services/$service/$compose_test_file"; then
            echo "Running test for ${{ matrix.service }}"
            docker-compose -f services/$service/$compose_test_file up --build --exit-code-from=gps_verify --abort-on-container-exit
          else
            echo "No test script found for service $service, skipping"
          fi
